repositories:
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com

releases:
- name: vault-operator
  namespace: vault
  chart: banzaicloud-stable/vault-operator
  version: 1.15.3
  wait: true
  values:
  - values.yaml

helmDefaults:
  kubeContext: k3d-k3s-default
  args:
  - --kubeconfig
  - "{{ env "HOME" }}/.k3d/k3s-default-config"